# Use the official Node.js image from the Docker Hub
FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY . .

# Install dependencies
RUN npm install
 


# Expose the port your app will run on
EXPOSE 3004


# Start the app
CMD ["npm", "start"]